select 'INCEPTION_DATE' GROUPING, INCEPTION_DATE GROUP_DETAIL, count(*) COUNT from Policy group by inception_date
select 'EXPIRY_DATE' GROUPING, EXPIRY_DATE GROUP_DETAIL, count(*) from Policy group by EXPIRY_DATE
select 'POST_CODE' GROUPING, POST_CODE GROUP_DETAIL, COUNT(*) FROM POLICY GROUP BY POST_CODE
select 'COUNTY' GROUPING, COUNTY GROUP_DETAIL, COUNT(*) FROM POLICY GROUP BY COUNTY;
select 'CARRIER NAME' GROUPING, carrier_name GROUP_DETAIL, count(*) from POLICY group by CARRIER_NAME;
select 'SCHEME_NAME' GROUPING, scheme_name GROUP_DETAIL, count(*) from POLICY group by scheme_NAME;
select 'FULL_T_COVER' GROUPING, FULL_T_COVER GROUP_DETAIL, count(*) from POLICY group by FULL_T_COVER